language: python
python:
    - "3.4"
    - "3.5"
install:
  - pip install -e .
  - pip install -r test/requirements.txt
script: pytest --cov=command_tree --cov-report term --cov-report xml --cov-report annotate
after_success:
  coveralls
